//! The plugin's error catalog, generated from the Rust protocol rather than
//! mirrored by hand.
//!
//! The two ends used to carry the same seventeen codes and messages in four
//! separate hand-written tables — `ERROR_CODES`' tuple type and its value list
//! (written twice inside TypeScript itself), `CANONICAL_MESSAGES`, and a second
//! copy of the messages in `read/render.ts`. Sixty-eight strings for seventeen
//! codes. Keeping them honest meant a Rust test that parsed TypeScript source
//! by splitting on colons and quotes, which in turn forced `prettier-ignore`
//! comments to keep entries on one line: a formatter run could otherwise wrap
//! an entry out of the parser's sight.
//!
//! Generating the file instead removes the parser, the formatting coupling and
//! three of the four tables. It follows the same generate-and-verify shape as
//! `tools_catalog.rs`: `UPDATE_SNAPSHOTS=1` writes the file, an ordinary run
//! asserts the committed copy still matches. Drift becomes a failing test with
//! a diff rather than a silent disagreement between two languages.

use figma_dev_mcp_protocol::error::{ErrorCode, canonical_message};

use super::error_code_tag;

const GENERATED: &str = "plugin/src/shared/error-catalog.ts";

fn plugin_root() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("tests crate has a workspace parent")
        .to_path_buf()
}

/// The file exactly as it should exist on disk.
///
/// Written by hand rather than through a templating crate because the output
/// is seventeen lines of two shapes, and a dependency to interpolate them
/// would be harder to audit than the strings themselves.
fn render_catalog() -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by tests/contracts/error_catalog.rs — do not edit by hand.\n\
         //\n\
         // Regenerate after changing `ErrorCode` or `canonical_message`:\n\
         //\n\
         //   UPDATE_SNAPSHOTS=1 cargo test -p figma-dev-mcp-tests --test contracts\n\
         //\n\
         // The Rust protocol is the single source for both lists. Editing this\n\
         // file directly makes the two ends disagree, which\n\
         // `the_plugin_error_catalog_is_generated_from_the_protocol` then fails\n\
         // on with a diff.\n\
         //\n\
         // This file is in .prettierignore: its bytes are fixed by the\n\
         // generator, and a formatter run would rewrite them into a mismatch.\n\
         \n\
         export const ERROR_CODES = [\n",
    );
    for code in ErrorCode::ALL {
        out.push_str(&format!("  \"{}\",\n", error_code_tag(code)));
    }
    out.push_str(
        "] as const\n\
         \n\
         export type ErrorCode = (typeof ERROR_CODES)[number]\n\
         \n\
         export const CANONICAL_MESSAGES: Record<ErrorCode, string> = {\n",
    );
    for code in ErrorCode::ALL {
        out.push_str(&format!(
            "  {}: \"{}\",\n",
            error_code_tag(code),
            canonical_message(code)
        ));
    }
    out.push_str("}\n");
    out
}

/// The generated catalog on disk is the one this protocol would produce.
///
/// A code added to `ErrorCode`, or a message reworded, fails here until the
/// file is regenerated — where the old arrangement failed in a mirror test
/// that first had to parse TypeScript to find out.
#[test]
fn the_plugin_error_catalog_is_generated_from_the_protocol() {
    let path = plugin_root().join(GENERATED);
    let rendered = render_catalog();
    if std::env::var("UPDATE_SNAPSHOTS").as_deref() == Ok("1") {
        std::fs::write(&path, &rendered).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{GENERATED} must exist: {error}"));
    assert_eq!(
        committed.replace("\r\n", "\n"),
        rendered,
        "\n{GENERATED} is not what this protocol generates.\n\
         Regenerate it:\n\
         \n  UPDATE_SNAPSHOTS=1 cargo test -p figma-dev-mcp-tests --test contracts\n"
    );
}

/// Every message the generator emits is the canonical one for its code.
///
/// The assertion above compares whole files, so a wrong message and a wrong
/// code would both read as "the file differs". This one says which of the two
/// the protocol actually holds, and is the pin that survives if the rendering
/// ever changes shape.
#[test]
fn the_generated_catalog_pairs_each_code_with_its_canonical_message() {
    let rendered = render_catalog();
    for code in ErrorCode::ALL {
        let entry = format!(
            "  {}: \"{}\",",
            error_code_tag(code),
            canonical_message(code)
        );
        assert!(
            rendered.contains(&entry),
            "generated catalog is missing the canonical pairing for {code:?}"
        );
    }
}
