// @generated by tests/contracts/error_catalog.rs — do not edit by hand.
//
// Regenerate after changing `ErrorCode` or `canonical_message`:
//
//   UPDATE_SNAPSHOTS=1 cargo test -p figma-dev-mcp-tests --test contracts
//
// The Rust protocol is the single source for both lists. Editing this
// file directly makes the two ends disagree, which
// `the_plugin_error_catalog_is_generated_from_the_protocol` then fails
// on with a diff.
//
// This file is in .prettierignore: its bytes are fixed by the
// generator, and a formatter run would rewrite them into a mismatch.

export const ERROR_CODES = [
  "NO_FIGMA_CONNECTION",
  "AMBIGUOUS_CONNECTION",
  "CONNECTION_NOT_FOUND",
  "CONNECTION_LOST",
  "PROTOCOL_MISMATCH",
  "NODE_NOT_FOUND",
  "NODE_NOT_VISIBLE",
  "PAGE_NOT_FOUND",
  "UNSUPPORTED_NODE",
  "EMPTY_NODE_BOUNDS",
  "CAPABILITY_UNAVAILABLE",
  "UNSAFE_SVG",
  "INVALID_CURSOR",
  "LIMIT_EXCEEDED",
  "TIMEOUT",
  "CANCELLED",
  "INTERNAL_ERROR",
] as const

export type ErrorCode = (typeof ERROR_CODES)[number]

export const CANONICAL_MESSAGES: Record<ErrorCode, string> = {
  NO_FIGMA_CONNECTION: "No Figma connection is available.",
  AMBIGUOUS_CONNECTION: "More than one Figma connection matches the request.",
  CONNECTION_NOT_FOUND: "The requested Figma connection was not found.",
  CONNECTION_LOST: "The Figma connection was lost.",
  PROTOCOL_MISMATCH: "The plugin protocol version is not supported.",
  NODE_NOT_FOUND: "The requested node was not found.",
  NODE_NOT_VISIBLE: "The requested node exists but is switched off, so it renders nothing.",
  PAGE_NOT_FOUND: "The requested page was not found.",
  UNSUPPORTED_NODE: "The requested node type is not supported.",
  EMPTY_NODE_BOUNDS: "The requested node renders nothing.",
  CAPABILITY_UNAVAILABLE: "The required Figma capability is unavailable.",
  UNSAFE_SVG: "The SVG was rejected by the safety policy.",
  INVALID_CURSOR: "The search cursor is invalid or stale.",
  LIMIT_EXCEEDED: "The operation exceeded a safety limit.",
  TIMEOUT: "The operation timed out.",
  CANCELLED: "The operation was cancelled.",
  INTERNAL_ERROR: "The operation failed.",
}
